### PR TITLE
:sparkles: pagination limit

### LINKED ISSUE #185: Specify pagination size on backend
Hello there,

I was wondering why the "size" query parameter was so uncontrolled. In my opinion it's quite dangerous to allow front end users to determine their size since they can crash your API.

I would have think of a new controller function like:

```php
function paginationSizes() {
  return [25, 50, 100];
}
```

It would be great to be able to provide params such as "< 1000" to just limit the size to a ceil.

What do you think ?

### PR DESCRIPTION
**Pull request by GautierDele**
closes #185

This basically allows to specify pagination limit and avoid possibility to crash your API or overuse the sql server.

TODO:

- [x] Documentation

### CODE REVIEW

File: src/Http/Controllers/BaseController.php [hunk 1]
```diff
@@ -89,6 +89,11 @@ abstract class BaseController extends \Illuminate\Routing\Controller
      */
     protected $queryBuilder;
 
+    /**
+     * @var int $paginationLimit
+     */
+    protected $paginationLimit = 500;
```
Comment (jasper-ter-veen) [inline src/Http/Controllers/BaseController.php:95]: Shouldn't this be an optional, configurable setting?

Comment (GautierDele) [reply src/Http/Controllers/BaseController.php:95]: I dont think so, you can increase the limit if you are willing to but if you dont need pagination you should use a non paginated controller in my opinion

Comment (jasper-ter-veen) [reply src/Http/Controllers/BaseController.php:95]: OK, Fair point. You can resolve this thread.

File: src/Http/Controllers/BaseController.php [hunk 2]
```diff
@@ -127,6 +132,7 @@ public function __construct()
             Paginator::class,
             [
                 'defaultLimit' => $this->limit(),
+                'maxLimit' => $this->paginationLimit
```
Comment (alexzarbn) [inline src/Http/Controllers/BaseController.php:135]: @GautierDele My OCD is suggesting to make it a method too, just like the `limit()` method 😄
Also, perhaps rename to `maxLimit()` to avoid confusion between those two.

**Review by alexzarbn — CHANGES_REQUESTED** [review]

File: src/Http/Controllers/BaseController.php (hunk 2 above)
Comment (GautierDele) [reply src/Http/Controllers/BaseController.php]: @alexzarbn that's done, I also changed a query param that wasn't good from previous PR

**Comment by GautierDele** [comment]
@alexzarbn doc has been updated in https://github.com/tailflow/laravel-orion-docs/pull/36
So you can change both if you want 😄

**Comment by GautierDele** [comment]
@alexzarbn also please notify in the upgrade guide that it could be a breaking change
We might want to update the middle version: v2.17.0

**Comment by alexzarbn** [comment]
@GautierDele  Awesome, thanks, merging ~
